<html>
<head><title></title></head>
<body>
<table>
    <tr>
        <td>Name:</td>
        <td>{{$name}}</td>
    </tr>
    <tr>
        <td>Email:</td>
        <td>{{$email}}</td>
    </tr>
    <tr>
        <td>Phone:</td>
        <td>{{$phone}}</td>
    </tr>
    <tr>
        <td>Message:</td>
        <td>{{$msg}}</td>
    </tr>
</table>

</body>
</html>
